# -*- coding: utf-8 -*-
"""
    These descriptions were obtained from the Apache SpamAssassin
    Wiki. http://wiki.apache.org/spamassassin/Rules

    These rule definitions have mostly been copied verbatim. However,
    some rules were confusing. As a result, some minor adjustments have
    been made to increase clarity.

    This text was made available by Apache via the GNU GPL, V2 license.
    http://www.gnu.org/licenses/gpl-2.0.html
"""

definitions = {
    "ADVANCE_FEE_2": "Appears to be advance fee fraud (Nigerian 419 - http://en.wikipedia.org/wiki/Nigerian_419_scammer)",
    "ADVANCE_FEE_3": "Appears to be advance fee fraud (Nigerian 419 - http://en.wikipedia.org/wiki/Nigerian_419_scammer)",
    "ADVANCE_FEE_4": "Appears to be advance fee fraud (Nigerian 419 - http://en.wikipedia.org/wiki/Nigerian_419_scammer)",
    "ALL_TRUSTED": "Passed through trusted hosts only via SMTP",
    "APOSTROPHE_FROM": "From address contains an apostrophe",
    "AWL": "WHITELISTING: From: address is in the auto white-list (http://wiki.apache.org/spamassassin/AutoWhitelist)",
    "BASE64_LENGTH_78_79": "Base64 body line(s) exceed 76 characters long. http://en.wikipedia.org/wiki/Base64",
    "BASE64_LENGTH_79_INF": "Base64 body line(s) exceed 76 characters long. http://en.wikipedia.org/wiki/Base64",
    "BAYES_00": "Bayes spam probability is 0 to 1%",
    "BAYES_05": "Bayes spam probability is 1 to 5%",
    "BAYES_20": "Bayes spam probability is 5 to 20%",
    "BAYES_40": "Bayes spam probability is 20 to 40%",
    "BAYES_50": "Bayes spam probability is 40 to 60%",
    "BAYES_60": "Bayes spam probability is 60 to 80%",
    "BAYES_80": "Bayes spam probability is 80 to 95%",
    "BAYES_95": "Bayes spam probability is 95 to 99%",
    "BAYES_99": "Bayes spam probability is 99 to 100%",
    "BLANK_LINES_70_80": "Message body has 70-80% blank lines",
    "BLANK_LINES_80_90": "Message body has 80-90% blank lines",
    "BLANK_LINES_90_100": "Message body has 90-100% blank lines",
    "CHARSET_FARAWAY": "Character set indicates a foreign language",
    "CHARSET_FARAWAY_HEADER": "A foreign language charset used in headers",
    "DATE_IN_FUTURE_03_06": "Date: is 3 to 6 hours after Received: date",
    "DATE_IN_FUTURE_06_12": "Date: is 6 to 12 hours after Received: date",
    "DATE_IN_FUTURE_12_24": "Date: is 12 to 24 hours after Received: date",
    "DATE_IN_FUTURE_24_48": "Date: is 24 to 48 hours after Received: date",
    "DATE_IN_FUTURE_48_96": "Date: is 48 to 96 hours after Received: date",
    "DATE_IN_FUTURE_96_XX": "Date: is 96 hours or more after Received: date",
    "DATE_IN_PAST_03_06": "Date: is 3 to 6 hours before Received: date",
    "DATE_IN_PAST_06_12": "Date: is 6 to 12 hours before Received: date",
    "DATE_IN_PAST_12_24": "Date: is 12 to 24 hours before Received: date",
    "DATE_IN_PAST_24_48": "Date: is 24 to 48 hours before Received: date",
    "DATE_IN_PAST_96_XX": "Date: is 96 hours or more before Received: date",
    "DC_GIF_UNO_LARGO": "Message contains a single large inline gif",
    "DC_IMAGE_SPAM_HTML": "Possible Image-only spam",
    "DC_IMAGE_SPAM_TEXT": "Possible Image-only spam with little text",
    "DIET_1": "Lose Weight Spam",
    "DKIM_ADSP_ALL": "Invalid DKIM: No valid author signature, domain signs all mail",
    "DKIM_ADSP_CUSTOM_HIGH": "No valid author signature, adsp_override is CUSTOM_HIGH",
    "DKIM_ADSP_CUSTOM_LOW": "No valid author signature, adsp_override is CUSTOM_LOW",
    "DKIM_ADSP_CUSTOM_MED": "No valid author signature, adsp_override is CUSTOM_MED",
    "DKIM_ADSP_DISCARD": "No valid author signature, domain signs all mail and suggests discarding the rest",
    "DKIM_ADSP_NXDOMAIN": "No valid author signature and domain not in DNS",
    "DKIM_POLICY_SIGNALL": "Domain Keys Identified Mail: Policy says domain signs all mails",
    "DKIM_POLICY_SIGNSOME": "Domain Keys Identified Mail: Policy says domain signs some mails",
    "DKIM_POLICY_TESTING": "Domain Keys Identified Mail: Policy says domain is testing DK",
    "DKIM_SIGNED": "Domain Keys Identified Mail: Message has a signature",
    "DKIM_VERIFIED": "Domain Keys Identified Mail: Signature passes verification",
    "DNS_FROM_DOB": "Sender from new domain (Day Old Bread)",
    "DNS_FROM_OPENWHOIS": "Ignore! This check is no longer valid.",
    "DNS_FROM_RFC_ABUSE": "Envelope sender in dsn.rfc-ignorant.org",
    "DNS_FROM_RFC_BOGUSMX": "Envelope sender in bogusmx.rfc-ignorant.org",
    "DNS_FROM_RFC_DSN": "Envelope sender in dsn.rfc-ignorant.org",
    "DNS_FROM_RFC_POST": "Envelope sender in postmaster.rfc-ignorant.org",
    "DNS_FROM_RFC_WHOIS": "Envelope sender in whois.rfc-ignorant.org",
    "DNS_FROM_SECURITYSAGE": "Envelope sender in blackholes.securitysage.com",
    "DOMAIN_RATIO": "Message body mentions too many internet domains",
    "DRUGS_ERECTILE": "Refers to an erectile drug (Viagra, Cialis, etc)",
    "DYN_RDNS_AND_INLINE_IMAGE": "Contains image, and was sent by dynamic rDNS",
    "EMAIL_ROT13": "Body contains a ROT13-encoded email address",
    "EXTRA_MPART_TYPE": "Header has extraneous Content-type:...type= entry",
    "FAKE_REPLY_C": "Subject contains 'Re:', but headers don't indicate a reply.",
    "FB_GAPPY_ADDRESS": "Body contains words written with spaces (F o o b a r)",
    "FB_SSEX": "Ignore! No longer used.",
    "FH_DATE_PAST_20XX": "The message creation date is too far in the future.",
    "FH_FROMEML_NOTLD": "E-mail address doesn't have TLD (.com, etc.)",
    "FH_HELO_ALMOST_IP": "Helo is almost an IP address, but doesn't appear fully valid",
    "FH_HELO_EQ_D_D_D_D": "Helo is valid d-d-d-d formatting",
    "FM_DOESNT_SAY_STOCK": "Appears to be stock market related spam",
    "FM_VIAGRA_SPAM1114": "Signs of a Viagra spam 11/14/2006",
    "FORGED_MSGID_HOTMAIL": "Message-ID is forged, (hotmail.com)",
    "FORGED_MUA_OUTLOOK": "Forged mail pretending to be from MS Outlook",
    "FORGED_OUTLOOK_HTML": "Outlook can't send HTML only emails",
    "FORGED_OUTLOOK_TAGS": "Outlook can't send HTML in this format",
    "FORGED_RCVD_HELO": "Received: Contains a forged HELO",
    "FORGED_YAHOO_RCVD": "'From' yahoo.com does not match 'Received' headers",
    "FREEMAIL_FROM": "Sent from a free email service provider",
    "FROM_BLANK_NAME": "From header contains a blank name.",
    "FROM_EXCESS_BASE64": "From: base64 encoded unnecessarily",
    "FROM_ILLEGAL_CHARS": "From: has too many raw illegal characters",
    "FROM_LOCAL_NOVOWEL": "From: localpart has series of non-vowel letters",
    "FROM_MISSPACED": "From: missing whitespace",
    "FS_NEW_XXX": "Subject looks like Pharmacy spam.",
    "FS_START_DOYOU2": "Subject starts with 'Do you dream, have, want, love, etc.'",
    "FUZZY_CPILL": "Attempt to obfuscate words in spam",
    "FUZZY_OCR": "Mail contains an image with common spam text inside",
    "FUZZY_XPILL": "Attempt to obfuscate words in spam",
    "GTUBE": "Generic Test for Unsolicited Bulk Email",
    "HABEAS_ACCREDITED_COI": "Habeas Accredited Confirmed Opt-In or Better",
    "HABEAS_ACCREDITED_SOI": "Habeas Accredited Opt-In or Better",
    "HABEAS_CHECKED": "Habeas Checked",
    "HASHCASH_20": "Contains valid Hashcash token (20 bits)",
    "HASHCASH_21": "Contains valid Hashcash token (21 bits)",
    "HASHCASH_22": "Contains valid Hashcash token (22 bits)",
    "HASHCASH_23": "Contains valid Hashcash token (23 bits)",
    "HASHCASH_24": "Contains valid Hashcash token (24 bits)",
    "HASHCASH_25": "Contains valid Hashcash token (25 bits)",
    "HASHCASH_2SPEND": "Hashcash token already spent in another mail",
    "HASHCASH_HIGH": "Contains valid Hashcash token (&gt; 25 bits)",
    "HELO_DYNAMIC_DHCP": "Relay HELO'd using suspicious hostname (DHCP)",
    "HELO_DYNAMIC_IPADDR": "Relay HELO'd using suspicious hostname (IP addr 1)",
    "HELO_DYNAMIC_IPADDR2": "Relay HELO'd using suspicious hostname (IP addr 2)",
    "HELO_LH_LD": "Poorly configured mail server. Helo is localhost instead of a valid domain.",
    "HS_INDEX_PARAM": "Link contains a common tracker pattern.",
    "HTML_EXTRA_CLOSE": "Malformed HTML: HTML contains too many close tags",
    "HTML_FONT_LOW_CONTRAST": "Attempted hidden text via low contrast colors.",
    "HTML_FONT_SIZE_HUGE": "HTML font size is unnecessarily large",
    "HTML_FONT_SIZE_LARGE": "HTML font size is unnecessarily large",
    "HTML_IMAGE_ONLY_04": "HTML: images with 0-400 bytes of words",
    "HTML_IMAGE_ONLY_08": "HTML: images with 400-800 bytes of words",
    "HTML_IMAGE_ONLY_12": "HTML: images with 800-1200 bytes of words",
    "HTML_IMAGE_ONLY_16": "HTML: images with 1200-1600 bytes of words",
    "HTML_IMAGE_ONLY_20": "HTML: images with 1600-2000 bytes of words",
    "HTML_IMAGE_ONLY_24": "HTML: images with 2000-2400 bytes of words",
    "HTML_IMAGE_ONLY_28": "HTML: images with 2400-2800 bytes of words",
    "HTML_IMAGE_ONLY_32": "HTML: images with 2800-3200 bytes of words",
    "HTML_IMAGE_RATIO_02": "HTML has a low ratio of text to images",
    "HTML_IMAGE_RATIO_04": "HTML has a low ratio of text to images",
    "HTML_IMAGE_RATIO_06": "HTML has a low ratio of text to images",
    "HTML_IMAGE_RATIO_08": "HTML has a low ratio of text to images",
    "HTML_MESSAGE": "HTML included in message",
    "HTML_MIME_NO_HTML_TAG": "HTML-only message, but there is no HTML tag",
    "HTML_MISSING_CTYPE": "Message is HTML without HTML Content-Type",
    "HTML_OBFUSCATE_05_10": "Message is 05% to 10% HTML obfuscation",
    "HTML_OBFUSCATE_10_20": "Message is 10% to 20% HTML obfuscation",
    "HTML_OBFUSCATE_20_30": "Message is 20% to 30% HTML obfuscation",
    "HTML_OBFUSCATE_30_40": "Message is 30% to 40% HTML obfuscation",
    "HTML_OBFUSCATE_50_60": "Message is 50% to 60% HTML obfuscation",
    "HTML_OBFUSCATE_70_80": "Message is 70% to 80% HTML obfuscation",
    "HTML_OBFUSCATE_90_100": "Message is 90% to 100% HTML obfuscation",
    "HTML_SHORT_LINK_IMG_2": "HTML is very short with a linked image",
    "HTML_SHORT_LINK_IMG_3": "HTML is very short with a linked image",
    "HTML_TAG_BALANCE_BODY": "HTML body tags are not balanced (i.e. no open and close)",
    "HTML_TAG_BALANCE_HTML": "HTML tags are not balanced (i.e. no open and close)",
    "HTTPS_IP_MISMATCH": "IP to HTTPS link found in HTML",
    "HTTP_ESCAPED_HOST": "Uses %-escapes inside a URL's hostname",
    "HTTP_EXCESSIVE_ESCAPES": "Completely unnecessary %-escapes inside a URL",
    "INTERRUPTUS": "Message looks to contain HTML-interrupted text",
    "INVALID_DATE": "Invalid Date: header (not RFC 2822)",
    "INVALID_DATE_TZ_ABSURD": "Invalid Date: header (timezone does not exist)",
    "INVALID_MSGID": "Message-Id is not valid, according to RFC 2822",
    "INVALID_TZ_CST": "Invalid date in header (wrong CST timezone)",
    "INVALID_TZ_EST": "Invalid date in header (wrong EST timezone)",
    "JM_REACTOR_MAILER": "Header patterns indicative of Reactor Mailer ratware",
    "MIME_BAD_ISO_CHARSET": "MIME character set is an unknown ISO charset",
    "MIME_BASE64_BLANKS": "Extra blank lines in base64 encoding",
    "MIME_BASE64_NO_NAME": "base64 attachment does not have a file name",
    "MIME_BASE64_TEXT": "Message text disguised using base64 encoding",
    "MIME_HEADER_CTYPE_ONLY": "'Content-Type' found without required MIME headers",
    "MIME_HTML_MOSTLY": "Multipart message mostly text/html MIME",
    "MIME_HTML_ONLY": "Non-Multipart: Message has only text/html MIME parts",
    "MIME_HTML_ONLY_MULTI": "Multipart message only has text/html MIME parts",
    "MIME_MISSING_BOUNDARY": "Malformed message: MIME section missing boundary",
    "MIME_QP_LONG_LINE": "Malformed message: Quoted-printable line longer than 76 chars",
    "MISSING_DATE": "Missing Date: header",
    "MISSING_HEADERS": "Missing To: header",
    "MISSING_MID": "Missing Message-Id: header",
    "MISSING_MIMEOLE": "Message has X-MSMail-Priority, but no X-MimeOLE",
    "MISSING_MIME_HB_SEP": "Missing blank line between MIME header and body",
    "MISSING_SUBJECT": "Missing Subject: header",
    "MPART_ALT_DIFF": "HTML and text parts are different",
    "MPART_ALT_DIFF_COUNT": "HTML and text parts are different",
    "MSGID_FROM_MTA_HEADER": "Message-Id was added by a relay",
    "MSGID_MULTIPLE_AT": "Message-ID contains multiple '@' characters",
    "MSGID_NO_HOST": "Message-Id has no hostname",
    "MSGID_OUTLOOK_INVALID": "Message-Id is fake (in Outlook Express format)",
    "MSGID_SPAM_CAPS": "Message-Id local part is in all caps.",
    "MSOE_MID_WRONG_CASE": "Message-Id does not appear to be from Outlook Express. However, headers indicate so.",
    "MULTIPART_ALT_NON_TEXT": "Multipart/alternative parts contains non-text parts",
    "NA_DOLLARS": "Mentions a million dollars. Typically a spammy phrase.",
    "NO_DNS_FOR_FROM": "Envelope sender has no MX or A DNS records",
    "NO_REAL_NAME": "From: does not include a real name",
    "NO_RELAYS": "Informational: Message was not relayed via SMTP",
    "NUMERIC_HTTP_ADDR": "Uses a numeric IP address in URL",
    "PART_CID_STOCK": "Has a spammy image attachment (by Content-ID)",
    "PLING_QUERY": "Subject has obnoxious exclamation or question marks",
    "PYZOR_CHECK": "BLACKLISTING: Listed in Pyzor (http://pyzor.sf.net/)",
    "RATWARE_MS_HASH": "Bulk email fingerprint (msgid ms hash) found",
    "RATWARE_OUTLOOK_NONAME": "Bulk email fingerprint (Outlook no name) found",
    "RAZOR2_CF_RANGE_51_100": "Razor2 provided confidence level above 50%",
    "RAZOR2_CF_RANGE_E4_51_100": "Razor2 provided engine 4 confidence level above 50%",
    "RAZOR2_CF_RANGE_E8_51_100": "Razor2 provided engine 8 confidence level above 50%",
    "RAZOR2_CHECK": "BLACKLISTING: Listed in Razor2 (http://razor.sf.net/)",
    "RCVD_BAD_ID": "Received: header contains unusually formatted ID",
    "RCVD_HELO_IP_MISMATCH": "HELO and IP do not match, but should",
    "RCVD_ILLEGAL_IP": "Received: contains illegal IP address",
    "RCVD_IN_BL_SPAMCOP_NET": "BLACKLISTING: RBL: Received via a relay in bl.spamcop.net",
    "RCVD_IN_BRBL_LASTEXT": "BLACKLISTING: Last external relay in Received chain in BRBL DNSBL",
    "RCVD_IN_BSP_OTHER": "BLACKLISTING: Sender is in Bonded Sender Program (other relay)",
    "RCVD_IN_BSP_TRUSTED": "WHITELISTING: Sender is in Sender Score Certified (trusted relay)",
    "RCVD_IN_DNSWL_HI": "WHITELISTING: Sender listed at http://www.dnswl.org/, high trust",
    "RCVD_IN_DNSWL_LOW": "WHITELISTING: Sender listed at http://www.dnswl.org/, low trust",
    "RCVD_IN_DNSWL_MED": "WHITELISTING: Sender listed at http://www.dnswl.org/, medium trust",
    "RCVD_IN_DNSWL_NONE": "WHITELISTING: Sender listed at http://www.dnswl.org/, no trust",
    "RCVD_IN_DOB": "Received via relay in new domain (Day Old Bread)",
    "RCVD_IN_DSBL": "BLACKLISTING: Received via a relay in list.dsbl.org",
    "RCVD_IN_IADB_VOUCHED": "ISIPP IADB lists as vouched-for sender",
    "RCVD_IN_MAPS_DUL": "BLACKLISTING: Relay in RBL, www.mail-abuse.org/rbl/",
    "RCVD_IN_MAPS_NML": "BLACKLISTING: Relay in NML, www.mail-abuse.org/nbl/",
    "RCVD_IN_MAPS_RBL": "BLACKLISTING: Relay in RBL, www.mail-abuse.org/rbl/",
    "RCVD_IN_MAPS_RSS": "BLACKLISTING: Relay in RSS, www.mail-abuse.org/rss/",
    "RCVD_IN_NJABL_CGI": "NJABL: sender is an open formmail",
    "RCVD_IN_NJABL_DUL": "NJABL: dialup sender performed non-local SMTP",
    "RCVD_IN_NJABL_MULTI": "NJABL: sent through multi-stage open relay",
    "RCVD_IN_NJABL_PROXY": "NJABL: sender is an open proxy",
    "RCVD_IN_NJABL_RELAY": "NJABL: sender is confirmed open relay",
    "RCVD_IN_NJABL_SPAM": "NJABL: sender is confirmed spam source",
    "RCVD_IN_PBL": "BLACKLISTING: Received via a relay in Spamhaus PBL",
    "RCVD_IN_PSBL": "BLACKLISTING: Received via a relay in PSBL",
    "RCVD_IN_RP_RNBL": "BLACKLISTING: Relay in RNBL, https://senderscore.org/blacklistlookup/",
    "RCVD_IN_SBL": "BLACKLISTING: Received via a relay in Spamhaus SBL",
    "RCVD_IN_SORBS_BLOCK": "SORBS: sender demands to never be tested by SORBS",
    "RCVD_IN_SORBS_DUL": "SORBS: sent directly from dynamic IP address",
    "RCVD_IN_SORBS_HTTP": "BLACKLISTING: SORBS: sender is open HTTP proxy server",
    "RCVD_IN_SORBS_SMTP": "BLACKLISTING: SORBS: sender is open SMTP relay ",
    "RCVD_IN_SORBS_SOCKS": "BLACKLISTING: SORBS: sender is open SOCKS proxy server",
    "RCVD_IN_SORBS_WEB": "BLACKLISTING: SORBS: sender is an abuseable web server",
    "RCVD_IN_SORBS_ZOMBIE": "BLACKLISTING: SORBS: sender is on a hijacked network",
    "RCVD_IN_XBL": "BLACKLISTING: Received via a relay in Spamhaus XBL",
    "RCVD_NUMERIC_HELO": "Received: contains an IP address used for HELO",
    "RDNS_DYNAMIC": "Delivered to trusted network by host with dynamic-looking rDNS",
    "RDNS_NONE": "Delivered to trusted network by a host with no rDNS",
    "REMOVE_BEFORE_LINK": "Removal phrase provided before the actual link",
    "REPTO_QUOTE_YAHOO": "Fake Yahoo! message. Yahoo doesn't do quoting like this",
    "RFC_ABUSE_POST": "Both abuse and postmaster missing on sender domain",
    "RP_MATCHES_RCVD": "Envelope sender domain matches handover relay domain",
    "SB_GIF_AND_NO_URIS": "Contains GIF image, but no URIs or email address",
    "SPAMMY_XMAILER": "X-Mailer string is common in spam and not in ham",
    "SPF_FAIL": "[FAIL] SPF: Sender does not match SPF record",
    "SPF_HELO_FAIL": "[FAIL] SPF: HELO does not match SPF record",
    "SPF_HELO_NEUTRAL": "[NEUTRAL] SPF: HELO does not match SPF record",
    "SPF_HELO_PASS": "[PASS] SPF: HELO matches SPF record",
    "SPF_HELO_SOFTFAIL": "[SOFT FAIL] SPF: HELO does not match SPF record",
    "SPF_NEUTRAL": "[NEUTRAL] SPF: Sender does not match SPF record",
    "SPF_PASS": "[PASS] SPF: Sender matches SPF record",
    "SPF_SOFTFAIL": "[SOFT FAIL] SPF: sender does not match SPF record",
    "STOX_REPLY_TYPE": "Mail content type is text/plain and has 'reply-type=original' attribute",
    "SUBJECT_FUZZY_TION": "Attempt to obfuscate words in Subject:",
    "SUBJECT_IN_BLACKLIST": "Subject: contains string in the user's black-list",
    "SUBJECT_NEEDS_ENCODING": "Subject: contains non-UTF8 characters and is not Base64 encoded",
    "SUBJ_ALL_CAPS": "Subject is all capitals",
    "SUBJ_ILLEGAL_CHARS": "Subject: has too many raw illegal characters",
    "SUBJ_RE_NUM": "Subject is faking 'The Bat!' responses",
    "SUSPICIOUS_RECIPS": "Similar addresses in recipient list",
    "TRACKER_ID": "Incorporates a tracking ID number",
    "TT_MSGID_TRUNC": "Message ID appears to be broken or invalid",
    "TVD_ACT_193": "Message includes a spammy string 'Act of 1930'",
    "TVD_APPROVED": "Message body contains 'you're approved'",
    "TVD_FINGER_02": "Message body contains invalid Content-Type and additional properties that appear spammy",
    "TVD_PH_BODY_ACCOUNTS_PRE": "Body contains known spammy buzz words (i.e. account suspended, account credited)",
    "TVD_RCVD_IP": "Validates Received: header chaining when relaying",
    "TVD_RCVD_IP4": "Received from an IPv4 relay with no reverse DNS.",
    "TVD_RCVD_SINGLE": "Message received from 'localhost'",
    "TVD_SPACE_RATIO": "Message contains words spaced vertically to hide spammy content",
    "T_RP_MATCHES_RCVD": "Envelope sender domain matches handover relay domain",
    "T_TO_NO_BRKTS_FREEMAIL": "FreeMail plugin is active.",
    "T_TVD_FW_GRAPHIC_ID1": "Message has Content-Id pattern that is spammy.",
    "UNIQUE_WORDS": "Message body has many words used only once",
    "UNPARSEABLE_RELAY": "Informational: message has unparseable relay lines",
    "UNWANTED_LANGUAGE_BODY": "Message written in an undesired language",
    "URG_BIZ": "Contains urgent matter",
    "URIBL_AB_SURBL": "BLACKLISTING: Contains an URL listed in the AB SURBL blocklist",
    "URIBL_BLACK": "BLACKLISTING: [Body] Contains an URL listed in the URIBL blacklist",
    "URIBL_BLOCKED": "Temporary URIBL lookup error",
    "URIBL_DBL_SPAM": "BLACKLISTING: Contains an URL listed in the DBL blocklist",
    "URIBL_GREY": "BLACKLISTING: Contains an URL listed in the URIBL greylist",
    "URIBL_JP_SURBL": "BLACKLISTING: Contains an URL listed in the JP SURBL blocklist",
    "URIBL_OB_SURBL": "BLACKLISTING: Contains an URL listed in the OB SURBL blocklist",
    "URIBL_RED": "BLACKLISTING: Contains an URL listed in the URIBL redlist",
    "URIBL_RHS_ABUSE": "BLACKLISTING: Contains an URI listed in abuse.rfc-ignorant.org",
    "URIBL_RHS_BOGUSMX": "BLACKLISTING: Contains an URI listed in bogusmx.rfc-ignorant.org",
    "URIBL_RHS_DOB": "BLACKLISTING: Contains an URI of a new domain (Day Old Bread) ",
    "URIBL_RHS_DSN": "BLACKLISTING: Contains an URI listed in dsn.rfc-ignorant.org ",
    "URIBL_RHS_POST": "BLACKLISTING: Contains an URI listed in postmaster.rfc-ignorant.org",
    "URIBL_RHS_TLD_WHOIS": "BLACKLISTING: Contains an URI TLD listed in whois.rfc-ignorant.org",
    "URIBL_RHS_WHOIS": "BLACKLISTING: Contains an URI listed in whois.rfc-ignorant.org",
    "URIBL_SBL": "BLACKLISTING: Contains an URL listed in the SBL blocklist",
    "URIBL_SC_SURBL": "BLACKLISTING: Contains an URL listed in the SC SURBL blocklist",
    "URIBL_WS_SURBL": "BLACKLISTING: Contains an URL listed in the WS SURBL blocklist",
    "USER_IN_DEF_WHITELIST": "WHITELISTING: From: address is in the default white-list",
    "USER_IN_WHITELIST": "WHITELISTING: From: address is in the user's white-list",
    "USER_IN_WHITELIST_TO": "WHITELISTING: User is listed in 'whitelist_to'",
    "US_DOLLARS_3": "Mentions millions of $ ($NN,NNN,NNN.NN)",
    "WEIRD_PORT": "Uses non-standard port number for HTTP",
    "WEIRD_QUOTING": "Strange repeated double-quotation marks",
    "WHOIS_DMNBYPROXY": "Contains URL registered to Domains by Proxy",
    "WHOIS_NETSOLPR": "URL registered as a NetSol Private Registration",
    "X_IP": "Message has X-IP header"
}
